# Configuration for SpeedMeter
# Version: 3.0
# Author: rnlin
#
# Enable / disable switch‼(true/false)
# default: true
# Get Speed frequency‼(1 ~ 500)
# default: 500
enablemeter: true
meterfrequency: 500
Allowed_World_Names:
   - world
   - world_the_end
   - world_nether