name: SpeedMeter
main: Meter.Speed.SpeedMeter
version: 3.1.2
author: rnlin
description: Speedmeter

commands:
  speedmeter:
    description: It's main commands of this plugin.
    aliases: [sm,speed,spm]
    usage: 
           /<command> [true|false] - 有効と無効を切り替えます。
           /<command> r <updatefrequency> - メーターの更新頻度を設定します。
           /<command> addmeter - スピードメーターの許可リストに今いるワールドを追加します。
           /<command> removemeter - スピードメーターの許可リストから今いるワールドを削除します。
           /<command> worldlist - スピードメーターの許可リスト一覧を表示します。
           /<command> elytra [true|false] - エリトラ装着時にy軸を速度に含めるかどうかを設定します。trueでエリトラ装着時以外はxz平面上の速度になります。   
           /<command> reload - すべての設定値をリロードします。    
    permisson: speed.meter.command.speedmeter
    permission-message: You don't have the permission "<permission>".
  meter:
    description: It's commands of this plugin.
    aliases: [mt]
    usage: /<command> [on|off] - メーターの表示を切り替えます
    permission: speed.meter.command.meter
    permission-message: You don't have the permission "<permission>".
  allmeter:
    description: It's commands of this plugin.
    aliases: [allmt,amt]
    usage: /<command> [on|off] - メーターの表示を切り替えます
    permission: speed.meter.speedmeter.allmeter
    permission-message: You don't have the permission "<permission>".   

permissions:
  speed.meter.command.speedmeter:
    description: speedmeterコマンドの使用権限
    default: op
  speed.meter.command.meter:
    description: meterコマンドの使用権限
    default: true
  speed.meter.speedmeter.boat:
    description: スピードメーター
    default: true
  speed.meter.speedmeter.allmeter:
    description: allmeterコマンドの使用権限
    default: true
